// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-2",
    "aws_cognito_identity_pool_id": "us-west-2:19fd1364-9f5b-487b-b169-5db0cf6e5a23",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_wfv5hw4OC",
    "aws_user_pools_web_client_id": "hsnlooj9jf4mnh7m40dcufpg4",
    "oauth": {
        "domain": "bt-web-dev.auth.us-west-2.amazoncognito.com",
        "scope": [
            "phone",
            "email",
            "openid",
            "profile",
            "aws.cognito.signin.user.admin"
        ],
        "redirectSignIn": "http://localhost:3000/login-redirect/",
        "redirectSignOut": "http://localhost:3000/",
        "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_POOLS"
};


export default awsmobile;