// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-2",
    "aws_cognito_identity_pool_id": "us-west-2:9e83a772-c088-4b4d-9ce0-d134e6524862",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_OEHytdXkv",
    "aws_user_pools_web_client_id": "1emgo259tli0tkhl7i58c81bo3",
    "oauth": {
        "domain": "asd-dev.auth.us-west-2.amazoncognito.com",
        "scope": [
            "phone",
            "email",
            "openid",
            "profile",
            "aws.cognito.signin.user.admin"
        ],
        "redirectSignIn": "http://localhost:3000/",
        "redirectSignOut": "http://localhost:3000/",
        "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_POOLS"
};


export default awsmobile;
